apache:
  build: ./apache
  container_name: apache
  ports:
    - "80:80"


busybox:
  image: busybox
  container_name: busybox
  volumes:
    - /opt/atlassian-home
    - /var/lib/postgresql/data
  command: echo data container


postgres:
  build: ./postgres
  container_name: postgres
  ports:
    - '5432:5432'
  volumes_from:
    - busybox


jira:
  build: ./jira
  container_name: jira
  ports:
    - "8080:8080"
  volumes_from:
    - busybox


bamboo:
  build: ./bamboo
  container_name: bamboo
  ports:
    - "8085:8085"
  volumes_from:
    - busybox


bitbucket:
  build: ./bitbucket
  container_name: bitbucket
  ports:
    - "7990:7990"
  volumes_from:
    - busybox
